# Generated by Django 5.0.2 on 2024-02-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_recipemodel_ingredients_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'ordering': ['title']},
        ),
    ]
