# Generated by Django 5.0.2 on 2024-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipes',
            field=models.ManyToManyField(to='main.recipemodel'),
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredient',
            field=models.ManyToManyField(to='main.ingredients'),
        ),
    ]
