# Generated by Django 5.0.2 on 2024-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ingredients_recipe_id_ingredients_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredient',
        ),
    ]
