# Generated by Django 5.0.2 on 2024-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_recipemodel_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient',
            field=models.ManyToManyField(blank=True, max_length=100, to='main.recipemodel'),
        ),
    ]
