# Generated by Django 5.0.2 on 2024-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ingredients_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
