# Generated by Django 5.0.2 on 2024-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ingredients_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.ManyToManyField(to='main.recipemodel'),
        ),
    ]
