# Generated by Django 5.0.2 on 2024-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ingredients_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ManyToManyField(to='main.recipemodel'),
        ),
    ]
